import type { Verdict } from '../types.ts';
import { type FilterConfig, IGNORED_SCHEMES } from './rules.ts';

export type FilterInput = {
  url: string;
  method: string;
  resourceType: string;
  /** Host of the top-level page, for first-party detection. May be null early on. */
  primaryHost: string | null;
  /** Only known once the response arrives; undefined during the request phase. */
  mimeType?: string;
};

/**
 * `ignore` is not the same as `drop`, and the difference matters a lot in
 * practice. A dropped request is real traffic from the site that we chose not to
 * surface — it is still recorded, still consumes a serial number, and is visible
 * under "show filtered-out" so the filter can be audited. An ignored request was
 * never the site's to begin with (this tool's own UI polling, a `data:` URI, a
 * browser extension), so recording it would be noise about ourselves.
 *
 * `maybe` means we cannot tell without the response content type; the recorder
 * holds such requests and re-evaluates once headers arrive.
 */
export type Stage = 'ignore' | 'drop' | 'keep' | 'maybe';

/**
 * Second-level domain suffixes that behave like a public suffix, so that
 * `acme.co.uk` is treated as the registrable domain rather than `co.uk`.
 * This is a deliberate approximation of the Public Suffix List: it covers the
 * common cases without shipping a 200KB data file we would then have to update.
 */
const MULTIPART_SUFFIXES = new Set([
  'co', 'com', 'net', 'org', 'gov', 'edu', 'ac', 'mil', 'gob', 'or', 'ne', 'go',
]);

/** Approximates eTLD+1, e.g. `app.acme.co.uk` -> `acme.co.uk`. */
export function registrableDomain(hostname: string): string {
  const labels = hostname.toLowerCase().split('.').filter(Boolean);
  if (labels.length <= 2) return labels.join('.');
  const secondLast = labels[labels.length - 2];
  const take = MULTIPART_SUFFIXES.has(secondLast) ? 3 : 2;
  return labels.slice(-take).join('.');
}

/** Exact-or-dot-suffix match, so `evil-sentry.io.example.com` is not a false hit. */
function domainMatches(hostname: string, patterns: string[]): string | null {
  const host = hostname.toLowerCase();
  for (const pattern of patterns) {
    const p = pattern.toLowerCase();
    if (host === p || host.endsWith('.' + p)) return pattern;
  }
  return null;
}

function extensionOf(pathname: string): string {
  const lastSegment = pathname.slice(pathname.lastIndexOf('/') + 1);
  const dot = lastSegment.lastIndexOf('.');
  return dot === -1 ? '' : lastSegment.slice(dot).toLowerCase();
}

function includesAny(haystack: string, needles: string[]): string | null {
  const lower = haystack.toLowerCase();
  for (const needle of needles) {
    if (lower.includes(needle.toLowerCase())) return needle;
  }
  return null;
}

export type StagedVerdict = Verdict & { stage: Stage };

/**
 * Decides whether a request is worth keeping, and always explains why.
 *
 * The reason string is surfaced verbatim in the UI. That is deliberate: a filter
 * whose decisions cannot be audited stops being trusted the first time something
 * the user expected to see is missing.
 */
export function evaluate(input: FilterInput, config: FilterConfig): StagedVerdict {
  const { url, method, resourceType, primaryHost, mimeType } = input;

  // Inline payloads and extension traffic are not network calls anyone can
  // replay, so they are dropped before a record is ever created for them.
  for (const scheme of IGNORED_SCHEMES) {
    if (url.startsWith(scheme)) {
      return { keep: false, stage: 'ignore', score: 0, reason: `ignored scheme ${scheme}` };
    }
  }

  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return { keep: false, stage: 'ignore', score: 0, reason: 'unparseable URL' };
  }

  const hostname = parsed.hostname;

  // An explicit allowlist beats every drop rule below it.
  const allowed = domainMatches(hostname, config.allowDomains);
  if (allowed) {
    return { keep: true, stage: 'keep', score: 100, reason: `allowlisted domain ${allowed}` };
  }

  // A CORS preflight is generated by the browser, never written by hand, and
  // answering it is the server's business rather than the wrapper's.
  if (method === 'OPTIONS' && !config.keepPreflight) {
    return { keep: false, stage: 'drop', score: 0, reason: 'CORS preflight' };
  }

  const noisyDomain = domainMatches(hostname, config.noiseDomains);
  if (noisyDomain) {
    return {
      keep: false,
      stage: 'drop',
      score: 0,
      reason: `known telemetry/CDN domain (${noisyDomain})`,
    };
  }

  if (config.alwaysDropTypes.includes(resourceType)) {
    return { keep: false, stage: 'drop', score: 0, reason: `resource type ${resourceType}` };
  }

  const extension = extensionOf(parsed.pathname);
  if (extension && config.noiseExtensions.includes(extension)) {
    return { keep: false, stage: 'drop', score: 0, reason: `static asset (${extension})` };
  }

  // XHR/Fetch/WebSocket/EventSource are the whole point of the tool. They are
  // kept regardless of which domain they target: private APIs very often live on
  // a different registrable domain than the page (app.acme.co.uk calls
  // gateway.acme-api.net), so a first-party-only rule would discard the payload.
  if (config.alwaysKeepTypes.includes(resourceType)) {
    const hint = includesAny(parsed.pathname, config.apiPathHints);
    return {
      keep: true,
      stage: 'keep',
      score: hint ? 90 : 70,
      reason: hint ? `${resourceType} matching ${hint}` : `${resourceType} request`,
    };
  }

  if (resourceType === 'Script' && !config.keepScripts) {
    return { keep: false, stage: 'drop', score: 0, reason: 'script bundle' };
  }

  if (resourceType === 'Document') {
    if (method !== 'GET') {
      return { keep: true, stage: 'keep', score: 60, reason: `${method} form submission` };
    }
    if (!config.keepDocuments) {
      return { keep: false, stage: 'drop', score: 0, reason: 'page navigation' };
    }
    return { keep: true, stage: 'keep', score: 20, reason: 'document (keepDocuments on)' };
  }

  const pathHint = includesAny(parsed.pathname, config.apiPathHints);
  if (pathHint) {
    return { keep: true, stage: 'keep', score: 80, reason: `API-shaped path (${pathHint})` };
  }

  // Nothing decisive so far. If the response has arrived we can settle it on
  // content type; if not, hold judgement so the body still gets fetched.
  if (mimeType === undefined) {
    return { keep: true, stage: 'maybe', score: 40, reason: 'pending response type' };
  }

  const mimeHint = includesAny(mimeType, config.dataMimeHints);
  if (mimeHint) {
    return { keep: true, stage: 'keep', score: 75, reason: `structured response (${mimeHint})` };
  }

  const isFirstParty =
    primaryHost !== null &&
    registrableDomain(hostname) === registrableDomain(primaryHost);

  return {
    keep: false,
    stage: 'drop',
    score: 0,
    reason: isFirstParty
      ? `non-data response (${mimeType || 'unknown type'})`
      : `third-party non-data response (${mimeType || 'unknown type'})`,
  };
}
